language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install

script: phpunit -c bin
