<?php

//Facebook AWD use his own autoloader.
//Maybe we should remove it and use the dedicated one in drupal
require_once('autoload.php');

use AHWEBDEV\FacebookAWD\FacebookAWD;

/**
 * Menu hook
 */
function facebookAWDDrupal_menu()
{
    $controller = drupal_container()->get('ahwebdev.facebook_awd.extension')->getExtension()->getBackendController();
    return $controller->adminMenu();
}

/**
 * Settings
 */
function facebokoAWD_settings($hook)
{
    $controller = drupal_container()->get('ahwebdev.facebook_awd.extension')->getExtension()->getBackendController();
    return $controller->content($hook);
}