<?php

//Facebook AWD use his own autoloader.
//Maybe we should remove it and use the dedicated one in drupal
require_once('autoload.php');

use AHWEBDEV\FacebookAWD\FacebookAWD;

/**
 * Menu hook
 */
function facebookAWDDrupal_menu()
{
    $controller = facebookAWDDrupalGetBridge()->getExtension()->getBackendController();
    return $controller->adminMenu();
}

/**
 * Settings
 */
function facebookAWDDrupal_settings($hook)
{
    $controller = facebookAWDDrupalGetBridge()->getExtension()->getBackendController();
    return $controller->content($hook);
}

/**
 * Return the extensionBridge interface
 * @return ExtensionBridgeInterface
 */
function facebookAWDDrupalGetBridge(){
    $extensionBridgeName = 'ahwebdev.facebook_awd.extension_bridge';
    return drupal_container()->get($extensionBridgeName);
}