<?php
namespace AHWEBDEV\FacebookAWD;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-31 at 02:33:39.
 */
class FacebookAWDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FacebookAWD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FacebookAWD;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::initServices
     * @todo   Implement testInitServices().
     */
    public function testInitServices()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::initListeners
     * @todo   Implement testInitListeners().
     */
    public function testInitListeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::initControllers
     * @todo   Implement testInitControllers().
     */
    public function testInitControllers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::registerPlugin
     * @todo   Implement testRegisterPlugin().
     */
    public function testRegisterPlugin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::registerAssets
     * @todo   Implement testRegisterAssets().
     */
    public function testRegisterAssets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::getInfos
     * @todo   Implement testGetInfos().
     */
    public function testGetInfos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::launch
     * @todo   Implement testLaunch().
     */
    public function testLaunch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::getTokenFormConfig
     * @todo   Implement testGetTokenFormConfig().
     */
    public function testGetTokenFormConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AHWEBDEV\FacebookAWD\FacebookAWD::boot
     * @todo   Implement testBoot().
     */
    public function testBoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
